language: php

php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  -travis_retry composer self-update
  -travis_retry composer install --prefer-source --dev --no-interaction

script: "vendor/bin/codecept run"
